# docker-compose.yml

version: '3.3'
services:
    product-service:
        restart: always
        build: ./product-service
        entrypoint: ["./product-service"]
        container_name: "product-service"
        ports:
        - 50051:50051
        links:
        - database
        depends_on:
        - database
        networks:
        - product-service-tier
        - backend-tier

    product-service-cli:
        build: ./product-service-cli
        entrypoint: ["./product-service-cli"]
        container_name: "product-service-cli"
        networks:
        - product-service-tier

    order-service:
        restart: always
        build: ./order-service
        entrypoint: ["./order-service"]
        container_name: "order-service"
        ports:
        - 50052:50051
        links:
        - database
        depends_on:
        - database
        networks:
        - order-service-tier
        - backend-tier

    order-service-cli:
        build: ./order-service-cli
        entrypoint: ["./order-service-cli"]
        container_name: "order-service-cli"
        networks:
        - order-service-tier

    payment-service:
        restart: always
        build: ./payment-service
        entrypoint: ["./payment-service"]
        container_name: "payment-service"
        ports:
        - 50053:50051
        links:
        - database
        depends_on:
        - database
        networks:
        - payment-service-tier
        - backend-tier

    payment-service-cli:
        build: ./payment-service-cli
        entrypoint: ["./payment-service-cli"]
        container_name: "payment-service-cli"
        networks:
        - payment-service-tier

    user-service:
        restart: always
        build: ./user-service
        entrypoint: ["./user-service"]
        container_name: "user-service"
        ports:
        - 50054:50051
        links:
        - database
        depends_on:
        - database
        networks:
        - user-service-tier
        - backend-tier

    user-service-cli:
        build: ./user-service-cli
        entrypoint: ["./user-service-cli"]
        container_name: "user-service-cli"
        networks:
        - user-service-tier

    auth-service:
        restart: always
        build: ./auth-service
        entrypoint: ["./auth-service"]
        container_name: "auth-service"
        ports:
        - 50055:50051
        networks:
        - auth-service-tier
        - backend-tier

    auth-service-cli:
        build: ./auth-service-cli
        entrypoint: ["./auth-service-cli"]
        container_name: "auth-service-cli"
        networks:
        - auth-service-tier

    database:
        image: postgres:latest
        ports:
        - 5434:5432
        volumes:
        - ./init-scripts:/docker-entrypoint-initdb.d
        networks:
        - product-service-tier
        - order-service-tier
        - payment-service-tier
        - user-service-tier

networks:
    product-service-tier:
    order-service-tier:
    payment-service-tier:
    user-service-tier:
    auth-service-tier:
    backend-tier: